export enum PlayState {
    SERVE_PLAYER_ONE = "SERVE_PLAYER_ONE",
    SERVE_PLAYER_TWO = "SERVE_PLAYER_TWO",
    TOWARDS_PLAYER_ONE = "TOWARDS_PLAYER_ONE",
    TOWARDS_PLAYER_TWO = "TOWARDS_PLAYER_TWO",
}